### ISSUE TITLE
Supports isSignalingNaN

### ISSUE THREAD

**Issue by plavelo** [dalance/softfloat-wrapper#3]
# Feature request
Supports isSignalingNaN.

# Detail
softfloat-sys has isSignalingNaN, but isSignalingNaN does not seem to be supported by this wrapper.

See also
https://salsa.debian.org/Kazan-team/softfloat-sys/-/blob/v0.1.3/src/lib.rs#L174

**Comment by dalance** [comment]
Thanks.
I added `is_signaling_nan` function and released v0.3.3.
